#!/usr/bin/env bash

# Requirements
# - [skim](https://github.com/lotabout/skim)
# - [bat](https://github.com/sharkdp/bat)

# Usage
# Copy file to a known path location or add to PATH
# execute in dir to see list of files and a preview of each

set -e

main() {
  previous_file="$1"
  file_to_edit=`select_file $previous_file`

  if [ -n "$file_to_edit" ] ; then
    "$EDITOR" "$file_to_edit"
    main "$file_to_edit"
  fi
}

select_file() {
  given_file="$1"
  # sk -c 'rg --files --hidden --no-binary' \
  rg --files --hidden --no-binary | sk \
    --preview='bat --style=plain --color=always --theme=ansi-dark {}' \
    --preview-window=right:70%:wrap \
    --query="$given_file"
}

main ""
